name: Test Manual Approval
on: workflow_dispatch

jobs:
  manual-approval-tester:
    runs-on: ubuntu-latest
    steps:
      - uses: bwvolleyball/manual-approval@main
        with:
          secret: ${{ github.TOKEN }}
          approvers: Bwvolleyball
          minimum-approvals: 1
          issue-title: "Test Manual Deployment"
          additional-approved-words: '#kaakaww,shipit,:shipit:,:white_check_mark:'
          additional-denied-words: ':x:'
